databases:
  - name: rootly_project_production
    databaseName: rootly_project_production
    user: shaun

services:
  - type: web
    name: rootly_challenge
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rootly_challenge_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false